import type { ReadingId } from "./readings.ts";

/**
 * The words for every outcome of every reading, in English and Japanese,
 * keyed "reading.outcome". `{braces}` are filled in from the outcome's
 * figures. They describe what the dice show and what the game makes of it,
 * and nothing about stakes: this package is used where children play.
 */
type Words = Record<`${ReadingId}.${string}`, string>;

export const READING_WORDS: { en: Words; ja: Words } = {
  en: {
    "sum.total": "{total}",
    "faces.faces": "",
    "scores.total": "{total}",
    "doubles.total": "{total}",
    "doubles.doubles": "{total}: doubles, so roll again",
    "doubles.third": "A third doubles in a row: the turn ends here",
    "robber.total": "{total}",
    "robber.seven": "Seven: the robber moves",
    "backgammon.moves": "Play a {a} and a {b}",
    "backgammon.doubles": "Double {face}s: play {face} four times",
    "sixAgain.move": "Move {face}",
    "sixAgain.again": "A six: move, and roll again",
    "sixAgain.third": "A third six in a row: no move, and the turn passes",
    "cowries.move": "{up} mouths up: move {move}",
    "cowries.grace": "{up} mouths up: move {move}, with a grace and another throw",
    "craps.natural": "{total} on the come-out: a natural",
    "craps.craps": "{total} on the come-out: craps",
    "craps.point": "{total} is the point",
    "craps.made": "{total}: the point is made",
    "craps.sevenOut": "Seven before the point of {point}: seven out",
    "craps.again": "{total}: roll again for the point of {point}",
    "hazard.nick": "{total} with a main of {main}: a nick",
    "hazard.out": "{total} with a main of {main}: out",
    "hazard.chance": "{total} is the chance; the main is {main}",
    "hazard.made": "{total}: the chance is thrown",
    "hazard.lost": "The main before the chance of {chance}: out",
    "hazard.again": "{total}: throw again for the chance of {chance}",
    "yahtzee.yahtzee": "Yahtzee: five {face}s",
    "yahtzee.large": "A large straight",
    "yahtzee.four": "Four of a kind, for {total}",
    "yahtzee.fullHouse": "A full house",
    "yahtzee.small": "A small straight",
    "yahtzee.three": "Three of a kind, for {total}",
    "yahtzee.chance": "Chance, for {total}",
    "pokerDice.five": "Five of a kind",
    "pokerDice.four": "Four of a kind",
    "pokerDice.fullHouse": "A full house",
    "pokerDice.straight": "A straight",
    "pokerDice.three": "Three of a kind",
    "pokerDice.twoPair": "Two pair",
    "pokerDice.pair": "A pair",
    "pokerDice.bust": "A bust",
    "farkle.scores": "Scores {score}",
    "farkle.farkle": "Farkle: nothing scores",
    "bunco.three": "Three {face}s: a Bunco in round {face}, a mini Bunco in any other",
    "bunco.count": "{dice}: a point for each die showing the round's number",
    "pig.turn": "{face}: the turn stands at {turn}",
    "pig.out": "A one: the turn scores nothing",
    "counts.counts": "{dice}",
    "shipCaptainCrew.none": "No ship yet: a 6 is needed",
    "shipCaptainCrew.ship": "A ship: a 5 is needed for the captain",
    "shipCaptainCrew.captain": "Ship and captain: a 4 is needed for the crew",
    "shipCaptainCrew.crew": "Ship, captain and crew, with a cargo of {cargo}",
    "shutTheBox.shut": "{total}: shut {ways}",
    "mexico.mexico": "Mexico",
    "mexico.doubles": "Double {face}s",
    "mexico.number": "{number}",
    "sicBo.big": "Big, with {total}",
    "sicBo.small": "Small, with {total}",
    "sicBo.triple": "Triple {face}s: neither big nor small",
    "choHan.cho": "Chō: {total} is even",
    "choHan.han": "Han: {total} is odd",
    "chinchirorin.pinzoro": "Pinzoro: three ones, the best hand",
    "chinchirorin.arashi": "Arashi: three {face}s",
    "chinchirorin.shigoro": "Shigoro: 4, 5, 6",
    "chinchirorin.hifumi": "Hifumi: 1, 2, 3",
    "chinchirorin.point": "A pair of {pair}s and a point of {point}",
    "chinchirorin.menashi": "Menashi: no hand, so throw again, up to three times",
    "risk.0-1": "The defender loses 1",
    "risk.1-0": "The attacker loses 1",
    "risk.0-2": "The defender loses 2",
    "risk.2-0": "The attacker loses 2",
    "risk.1-1": "Each side loses 1",
    "risk.0-0": "Nothing to compare: each side needs a die",
    "highest.first": "Player {player} goes first, with a {face}",
    "highest.tie": "Players {players} tie on {face}: they roll again",
    "d20.natural20": "A natural 20, for {total}",
    "d20.natural1": "A natural 1, for {total}",
    "d20.total": "{total}",
    "fate.rung8": "Legendary ({total})",
    "fate.rung7": "Epic ({total})",
    "fate.rung6": "Fantastic ({total})",
    "fate.rung5": "Superb ({total})",
    "fate.rung4": "Great ({total})",
    "fate.rung3": "Good ({total})",
    "fate.rung2": "Fair ({total})",
    "fate.rung1": "Average ({total})",
    "fate.rung0": "Mediocre ({total})",
    "fate.rung-1": "Poor ({total})",
    "fate.rung-2": "Terrible ({total})",
    "fate.above": "{total}: past the top of the ladder",
    "fate.below": "{total}: below the foot of the ladder",
    "bladesPool.critical": "A critical: you do it with increased effect",
    "bladesPool.six": "A 6: you do it",
    "bladesPool.partial": "A {top}: you do it, but there is a consequence",
    "bladesPool.bad": "A {top}: things go badly",
    "pbta.strong": "{total}: a full success",
    "pbta.weak": "{total}: a success at a cost",
    "pbta.miss": "{total}: a miss",
    "successes.hits": "{hits} successes",
    "successes.one": "1 success",
    "successes.none": "No successes",
    "hitsAndGlitch.hits": "{hits} hits",
    "hitsAndGlitch.one": "1 hit",
    "hitsAndGlitch.none": "No hits",
    "hitsAndGlitch.glitch": "A glitch (hits: {hits}): more than half the dice show a one",
    "percentile.under": "{total}: a success for a skill of {total} or more, hard for {hard} or more, extreme for {extreme} or more",
    "rollUnder.under": "{total}: a success for a skill of {total} or more",
    "rollUnder.critical": "{total}: always a critical success",
    "rollUnder.fail": "17: a failure, and a critical one for a skill of 15 or less",
    "rollUnder.fumble": "18: always a critical failure",
    "d66.number": "{number}",
  },
  ja: {
    "sum.total": "{total}",
    "faces.faces": "",
    "scores.total": "{total}",
    "doubles.total": "{total}",
    "doubles.doubles": "{total}: ゾロ目です。もう一度振ります",
    "doubles.third": "3回続けてゾロ目です。手番はここで終わります",
    "robber.total": "{total}",
    "robber.seven": "7: 盗賊が動きます",
    "backgammon.moves": "{a} と {b} を使います",
    "backgammon.doubles": "{face} のゾロ目: {face} を4回使います",
    "sixAgain.move": "{face} 進みます",
    "sixAgain.again": "6: 進んで、もう一度振ります",
    "sixAgain.third": "3回続けて6です。進めず、手番が移ります",
    "cowries.move": "表が {up} 個: {move} 進みます",
    "cowries.grace": "表が {up} 個: {move} 進み、もう一度投げます",
    "craps.natural": "カムアウトで {total}: ナチュラルです",
    "craps.craps": "カムアウトで {total}: クラップスです",
    "craps.point": "{total} がポイントです",
    "craps.made": "{total}: ポイントが出ました",
    "craps.sevenOut": "ポイント {point} の前に7: セブンアウトです",
    "craps.again": "{total}: ポイント {point} を目指してもう一度振ります",
    "hazard.nick": "メイン {main} で {total}: ニックです",
    "hazard.out": "メイン {main} で {total}: アウトです",
    "hazard.chance": "{total} がチャンスです（メインは {main}）",
    "hazard.made": "{total}: チャンスが出ました",
    "hazard.lost": "チャンス {chance} の前にメイン: アウトです",
    "hazard.again": "{total}: チャンス {chance} を目指してもう一度振ります",
    "yahtzee.yahtzee": "ヤッツィー: {face} が5個",
    "yahtzee.large": "ラージストレート",
    "yahtzee.four": "フォーカード（{total} 点）",
    "yahtzee.fullHouse": "フルハウス",
    "yahtzee.small": "スモールストレート",
    "yahtzee.three": "スリーカード（{total} 点）",
    "yahtzee.chance": "チャンス（{total} 点）",
    "pokerDice.five": "ファイブカード",
    "pokerDice.four": "フォーカード",
    "pokerDice.fullHouse": "フルハウス",
    "pokerDice.straight": "ストレート",
    "pokerDice.three": "スリーカード",
    "pokerDice.twoPair": "ツーペア",
    "pokerDice.pair": "ワンペア",
    "pokerDice.bust": "役なし",
    "farkle.scores": "{score} 点",
    "farkle.farkle": "ファークル: 得点になる目がありません",
    "bunco.three": "{face} が3個: ラウンド {face} ならバンコ、ほかのラウンドならミニバンコです",
    "bunco.count": "{dice}: ラウンドの数字と同じ目1個につき1点",
    "pig.turn": "{face}: この手番の合計は {turn}",
    "pig.out": "1: この手番は0点です",
    "counts.counts": "{dice}",
    "shipCaptainCrew.none": "船がありません。6が必要です",
    "shipCaptainCrew.ship": "船があります。船長の5が必要です",
    "shipCaptainCrew.captain": "船と船長がそろいました。乗組員の4が必要です",
    "shipCaptainCrew.crew": "船・船長・乗組員がそろいました。積み荷は {cargo}",
    "shutTheBox.shut": "{total}: 閉じられる札は {ways}",
    "mexico.mexico": "メキシコ",
    "mexico.doubles": "{face} のゾロ目",
    "mexico.number": "{number}",
    "sicBo.big": "大（{total}）",
    "sicBo.small": "小（{total}）",
    "sicBo.triple": "{face} のゾロ目: 大でも小でもありません",
    "choHan.cho": "丁（{dice}、合計 {total}）",
    "choHan.han": "半（{dice}、合計 {total}）",
    "chinchirorin.pinzoro": "ピンゾロ（1・1・1）",
    "chinchirorin.arashi": "アラシ（{face} のゾロ目）",
    "chinchirorin.shigoro": "シゴロ（4・5・6）",
    "chinchirorin.hifumi": "ヒフミ（1・2・3）",
    "chinchirorin.point": "{pair} のペアで、目は {point}",
    "chinchirorin.menashi": "目なし: もう一度振ります（3回まで）",
    "risk.0-1": "守備側が1失います",
    "risk.1-0": "攻撃側が1失います",
    "risk.0-2": "守備側が2失います",
    "risk.2-0": "攻撃側が2失います",
    "risk.1-1": "双方が1ずつ失います",
    "risk.0-0": "比べるダイスがありません。双方に1個ずつ必要です",
    "highest.first": "{player} 番のプレイヤーが先攻です（出目 {face}）",
    "highest.tie": "{players} 番のプレイヤーが {face} で同点です。振り直します",
    "d20.natural20": "出目20（合計 {total}）",
    "d20.natural1": "出目1（合計 {total}）",
    "d20.total": "{total}",
    "fate.rung8": "Legendary（{total}）",
    "fate.rung7": "Epic（{total}）",
    "fate.rung6": "Fantastic（{total}）",
    "fate.rung5": "Superb（{total}）",
    "fate.rung4": "Great（{total}）",
    "fate.rung3": "Good（{total}）",
    "fate.rung2": "Fair（{total}）",
    "fate.rung1": "Average（{total}）",
    "fate.rung0": "Mediocre（{total}）",
    "fate.rung-1": "Poor（{total}）",
    "fate.rung-2": "Terrible（{total}）",
    "fate.above": "{total}: ラダーの上限を超えています",
    "fate.below": "{total}: ラダーの下限より下です",
    "bladesPool.critical": "クリティカル: 成功し、効果が上がります",
    "bladesPool.six": "6: 成功です",
    "bladesPool.partial": "{top}: 成功ですが、代償があります",
    "bladesPool.bad": "{top}: うまくいきません",
    "pbta.strong": "{total}: 完全な成功です",
    "pbta.weak": "{total}: 代償のある成功です",
    "pbta.miss": "{total}: 失敗です",
    "successes.hits": "成功数 {hits}",
    "successes.one": "成功数 1",
    "successes.none": "成功なし",
    "hitsAndGlitch.hits": "ヒット {hits}",
    "hitsAndGlitch.one": "ヒット 1",
    "hitsAndGlitch.none": "ヒットなし",
    "hitsAndGlitch.glitch": "グリッチ（ヒット {hits}）: ダイスの半分より多くが1です",
    "percentile.under": "{total}: 技能値 {total} 以上で成功、{hard} 以上でハード成功、{extreme} 以上でイクストリーム成功",
    "rollUnder.under": "{total}: 技能値 {total} 以上で成功",
    "rollUnder.critical": "{total}: 必ずクリティカル成功です",
    "rollUnder.fail": "17: 失敗です。技能値15以下ならクリティカル失敗です",
    "rollUnder.fumble": "18: 必ずクリティカル失敗です",
    "d66.number": "{number}",
  },
};
